### ISSUE TITLE
Application Not Found when logged with non admin user

### ISSUE THREAD

**Issue by gferrette** [opendistro-for-elasticsearch/security-kibana-plugin#643]
Hello!

Please, i've made an upgrade from Opendistro 1.0.2 to Opendistro 1.11 and i'm getting the message "Application Not Found" when i try to login with a non admin user, for example internal user, as the image:

![image](https://user-images.githubusercontent.com/44647577/101215170-1c065400-365c-11eb-89c6-d0981748dc72.png)

Is there any configuration that i am missing?

Thanks in advance!

Gabriel.

**Comment by yuxitang-amzn** [comment]
Duplicate of https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/639

**Comment by yuxitang-amzn** [comment]
Hi @gferrette, 

This should be a duplicate issue that already fixed (I'm not sure which one it actually is since the screenshot doesn't include the url). We didn't have a release for the fix. You may wait for our next release or try build from source.

I'm going to close this issue. Feel free to re-open if you have further questions.

**Comment by gferrette** [comment]
Hello @yuxitang-amzn !

Thanks for replying! Please, is there a date for the next release?
Do you know where can i find documentation to build from source?

Thanks in advance!

**Comment by yuxitang-amzn** [comment]
@gferrette 

The next release 1.12 will be soon while it is for kibana 7.10.

For building from source, please have a look at this build section in readme:
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin#build
