### ISSUE TITLE
Kibana Security Plugin not re-requesting token from Azure and reseting users to default Private Tenant

### ISSUE THREAD

**Issue by verbecee** [opendistro-for-elasticsearch/security-kibana-plugin#655]
I help support a 100+ node Elasticsearch cluster, and we recently upgraded from ES version 7.4 to ES v 7.12.0 and are using Kibana v 1.4.0. We have had one issue with the Kibana security plugin for awhile, and a new one has cropped up and is exacerbated by the first issue. 

**Security Plugin not re-requesting token from Azure**
In our environment, we use Azure for authentication and our IAM team has set a token timeout of 1 hour. Kibana either doesn't re-request the token or there is a bug in the request. I can't see any errors or logs in my Kibana logs that suggest the request is erroring out. Some extra guidance on triaging on this would be helpful.

**Users are reverted back to Private tenant after token expires (or kibana crashes)**
Prior to this upgrade, when a user would log into Kibana, whatever tenant they had used in their prior session persisted. I.e., if Kibana crashed or their token timed out, the user would stay in their current tenant. Now, whenever a user logs back into Kibana post-upgrade, they are sent back to their private tenant. Given how often tokens expire (every hour) and/or Kibana crashes, a user is having to sign back into their tenant 7+ times a day. In our environment, we have 30+ users who use the same tenant that has all their index patterns, dashboards, etc.

**Comment by yuxitang-amzn** [comment]
Hi @verbecee 

Could you confirm the version you are using? Since ES 7.12 is not available yet and usually kibana version is paired with ES.
Elasticsearch version:
Kibana version:
Opendistro version:

> Users are reverted back to Private tenant after token expires (or kibana crashes)  
I believe prior to 1.10, the tenant selection will be saved in cookie for some time like 1 day. In 1.10 and 1.11 we didn't implemented the saving yet. It is requested in https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/615 and WIP.
Instead if you have access to kibana.yml you can the update the `opendistro_security.multitenancy.tenants.preferred` (which is `["Private", "Global"]` by default). Ref: `https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/

**Comment by brian-grabau** [comment]
We (verbecee) are on opendistro 1.12 and elastic 7.10

**Comment by verbecee** [comment]
@yuxitang-amzn any idea of when this will be fixed? Our users getting kicked back into their private tenant every 20 minutes, it's incredibly frustrating for our end users.

**Comment by brian-grabau** [comment]
Yes super annoying (super unusable), we also see users loosing browser time offset,  Not sure if related but seems to be lots of issues with settings persisting.

**Comment by yuxitang-amzn** [comment]
For the tenant part, 2 options:
1) If most of your users are using same tenant (like global), as I mentioned above, you can update the `opendistro_security.multitenancy.tenants.preferred` in kibama.yml config.
2) We have pushed a PR https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/650 to allow user to save their tenant selection. It will be included in next release. Meanwhile you can build from source yourselves.

**Comment by verbecee** [comment]
Thanks @yuxitang-amzn ... we ended up disabling both global and dumping our users into a common tenant. We'll be on the lookout for that release.
