### ISSUE TITLE
OIDC - 401 Error Login URL Open Distro 1.12

### ISSUE THREAD

**Issue by ogallart** [opendistro-for-elasticsearch/security-kibana-plugin#672]
Hi!

Today I'm trying to update from ODFE 1.9 to 1.12 that i'm using with keycloak. 

But after kibana starts, when I'm try to login, the login URL not work anymore. It was changed since ODFE 1.9 or it's an error?

http://localhost:5601/auth/openid/login

**Comment by Hokwang** [comment]
@ogallart did you solve this?

**Comment by ogallart** [comment]
@Hokwang not, i can't solve it yet.

I'm waiting for a new release if they solve it.

I create a topic in the community too:

https://discuss.opendistrocommunity.dev/t/openid-with-opendisto-1-12/4551

**Comment by mbchris** [comment]
I'm having the same issue here.

OpenDistro for ElasticSearch 1.12 + OpenDistro Kibana 1.12 => `{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}`   . When trying to login into Kibana, there is no redirect to the Identity Provider. It's directly answering with a http 401 (instead of a 301 redirect) - can clearly see this in the browser debug traces. Kibana log doesn't show anything helpful in debug mode. 

Strange thing:

On **first** Kibana start (of the docker container based on the official image), it works **when the .kibana index is not present**. 

When I restart the container, the problem is there.

Going back to 1.11 OpenDistro Kibana (with 1.12 ElasticSearch) works.
Using any other authorization method (BasicAuth or Proxy) also works.

**Comment by alantang888** [comment]
I got the same issue. After I upgrade kibana from 1.9 to 1.12 also have 401 issue. But I downgrade to 1.11 also have 401 issue. I using `opendistro_security.auth.type: proxy`.

**Comment by alantang888** [comment]
I found need to add `opendistro_security.proxycache.user_header` to kibana.yml to make it work.

**Comment by ogallart** [comment]
I close the issue because using the 1.13.1 version I can confirm that it works again, so it's not an issue now.
